name: Build Kivy Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Git user
      run: |
       git config --global user.email "ozmatox@gmail.com"
       git config --global user.name "ozmatox"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-setuptools python3-venv \
            git zip unzip openjdk-17-jdk autoconf automake libtool pkg-config \
            cmake libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

    - name: Create virtual environment
      run: python3 -m venv venv

    - name: Install buildozer
      run: |
        ./venv/bin/python -m pip install --upgrade pip
        ./venv/bin/python -m pip install cython buildozer

    - name: Build APK
      run: |
        ./venv/bin/python -m buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: lotto-app-apk
        path: bin/*.apk
