name: Build Kivy Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf automake \
          libtool pkg-config cmake libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

    - name: Remove old venv (safety)
      run: rm -rf venv

    - name: Create virtual environment
      run: python -m venv venv

    - name: Check virtualenv python
      run: venv/bin/python --version

    - name: Install Buildozer and Kivy
      run: |
        venv/bin/python -m pip install --upgrade pip
        venv/bin/python -m pip install cython buildozer kivy

    - name: Build APK
      run: venv/bin/python -m buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: lotto-app-apk
        path: bin/*.apk
